name: Common Build Workflow

on:
  workflow_call:
    inputs:
      environment: 
        description: "Environment"
        type: string
        required: true
      docker_image_name:
        description: "Name of the Docker image to build"
        type: string
        required: true
      test_directory:
        type: string
        description: "Directory containing unit tests"
        default: "tests"
        required: true
      run_tests_job:
        description: "Flag to determine if the tests job should run"
        type: boolean
        required: false
        default: true
      build_job:
        description: "Flag to determine if the build job should run"
        type: boolean
        required: false
        default: true
      push_job:
        type: boolean
        description: "Flag to determine if the push job should run"
        required: false
        default: true
    secrets:
      docker_username:
        description: "Docker Hub username"
      docker_password:
        description: "Docker Hub password"

jobs:
  setup-environment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Environment
        uses: ./.github/actions/setup-environment
        with:
          environment: ${{ inputs.environment }}

      - name: Unit Tests
        uses: "./.github/actions/tests"

  build-docker:
    runs-on: ubuntu-latest
    needs: setup-environment
    if: ${{ inputs.build_job == 'true' }}
    steps:
      - name: Build Docker Image
        run: docker build -t ${{ secrets.docker_username }}/${{ inputs.docker_image_name }}:latest .

  # push-docker:
  #   runs-on: ubuntu-latest
  #   needs: build-docker
  #   if: ${{ inputs.push_job == 'true' }}
  #   steps:
  #     - name: Log in to Docker Hub
  #       uses: docker/login-action@v2
  #       with:
  #         username: ${{ secrets.docker_username }}
  #         password: ${{ secrets.docker_password }}

  #     - name: Push Docker Image
  #       run: docker push ${{ secrets.docker_username }}/${{ inputs.docker_image_name }}:latest
